export const jumioVerificationReq = `{
  "Data": {
    "JumioResponse": {
      "callBackType": callBackType,
      "callbackDate": callbackDate,
      "clientIp": clientIp,
      "customerId": customerId,
      "firstAttemptDate": firstAttemptDate,
      "optionalData1": optionalData1 ? optionalData1 : '',
      "optionalData2": optionalData2 ? optionalData2 : '',
      "dni": dni ? dni : '',
      "gender": gender ? gender : '',
      "presetCountry": presetCountry ? presetCountry : '',
      "presetIdType": presetIdType ? presetIdType : '',
      "originDob": originDob ? originDob : '',
      "idAddress": {
        "city": idAddress.city,
        "country": idAddress.country,
        "stateCode": idAddress.stateCode,
        "streetName": idAddress.streetName,
        "streetNumber": idAddress.streetNumber,
        "unitDesignator": idAddress.unitDesignator ? idAddress.unitDesignator : '',
        "unitNumber": idAddress.unitNumber ? idAddress.unitNumber : '',
        "streetSuffix": idAddress.streetSuffix,
        "streetDirection": idAddress.streetDirection,
        "zip": idAddress.zip,
        "zipExtension": idAddress.zipExtension ? idAddress.zipExtension : ''
      },
      "merchantIdScanReference": merchantIdScanReference,
      "merchantReportingCriteria": merchantReportingCriteria ? merchantReportingCriteria : '',
      "idCheckDataPositions": "OK",
      "idCheckDocumentValidation": "OK",
      "idCheckHologram": "OK",
      "idCheckMRZcode": idCheckMRZcode,
      "idCheckMicroprint": "OK",
      "idCheckSecurityFeatures": "OK",
      "idCheckSignature": "OK",
      "idCountry": idCountry,
      "idDob": idDob,
      "idExpiry": idExpiry,
      "idFirstName": idFirstName,
      "idLastName": idLastName,
      "idNumber": idNumber,
      "idScanImage": idScanImage,
      "idScanImageBackside": idScanImageBackside,
      "idScanImageFace": idScanImageFace,
      "idScanSource": idScanSource,
      "idScanStatus": "SUCCESS",
      "idType": idType,
      "idSubtype": idSubtype ? idSubtype : '',
      "idUsState": idUsState,
      "personalNumber": personalNumber ? personalNumber : '',
      "identityVerification": {
        "similarity": "MATCH",
        "validity": true,
        "reason": "SELFIE_CROPPED_FROM_ID",
        "handwrittenNoteMatches": true
      },
      "jumioIdScanReference": jumioIdScanReference,
      "livenessImages": livenessImages ? livenessImages : [],
      "placeOfBirth": placeOfBirth ? placeOfBirth : '',
      "transactionDate": transactionDate,
      "verificationStatus": "APPROVED_VERIFIED"
    }
  }
}`;
